
-- 部署
INSERT INTO DIVISION(ID, NAME) VALUES ('D01', '総務部');
INSERT INTO DIVISION(ID, NAME) VALUES ('D02', '営業部');
INSERT INTO DIVISION(ID, NAME) VALUES ('D03', '開発部');

-- 従業員
INSERT INTO EMPLOYEE (ID, NAME, AGE, GENDER, PHOTO_ID, POSTAL_CODE, PREF,CITY,ADDRESS, DIV_ID) VALUES('EMP0001', '山田　太郎', 35, '男', 'P00001', '100-1000', '東京都','千代田区','', 'D01');
INSERT INTO EMPLOYEE (ID, NAME, AGE, GENDER, PHOTO_ID, POSTAL_CODE, PREF,CITY, ADDRESS, DIV_ID) VALUES('EMP0002', '日本　花子', 27, '女', 'P00002', '200-2000','埼玉県','さいたま市','', 'D02');
INSERT INTO EMPLOYEE (ID, NAME, AGE, GENDER, PHOTO_ID, POSTAL_CODE, PREF,CITY, ADDRESS, DIV_ID) VALUES('EMP0003', '東京　次郎', 41, '男', 'P00003', '300-3000','神奈川県','川崎市高津区','菅生', 'D01');

-- 都道府県
INSERT INTO PREF (ID, NAME) VALUES (1,'北海道');
INSERT INTO PREF (ID, NAME) VALUES (2,'青森県');
INSERT INTO PREF (ID, NAME) VALUES (3,'岩手県');
INSERT INTO PREF (ID, NAME) VALUES (4,'秋田県');
INSERT INTO PREF (ID, NAME) VALUES (5,'山形');
INSERT INTO PREF (ID, NAME) VALUES (6,'宮城県');
INSERT INTO PREF (ID, NAME) VALUES (7,'福島県');
INSERT INTO PREF (ID, NAME) VALUES (8,'茨城県');
INSERT INTO PREF (ID, NAME) VALUES (9,'栃木県');
INSERT INTO PREF (ID, NAME) VALUES (10,'群馬県');
INSERT INTO PREF (ID, NAME) VALUES (11,'埼玉県');
INSERT INTO PREF (ID, NAME) VALUES (12,'千葉県');
INSERT INTO PREF (ID, NAME) VALUES (13,'東京都');
INSERT INTO PREF (ID, NAME) VALUES (14,'神奈川県');
INSERT INTO PREF (ID, NAME) VALUES (15,'新潟県');
INSERT INTO PREF (ID, NAME) VALUES (16,'富山県');
INSERT INTO PREF (ID, NAME) VALUES (17,'石川県');
INSERT INTO PREF (ID, NAME) VALUES (18,'福井県');
INSERT INTO PREF (ID, NAME) VALUES (19,'山梨県');
INSERT INTO PREF (ID, NAME) VALUES (20,'長野県');
INSERT INTO PREF (ID, NAME) VALUES (21,'岐阜県');
INSERT INTO PREF (ID, NAME) VALUES (22,'静岡県');
INSERT INTO PREF (ID, NAME) VALUES (23,'愛知県');
INSERT INTO PREF (ID, NAME) VALUES (24,'三重県');
INSERT INTO PREF (ID, NAME) VALUES (25,'滋賀県');
INSERT INTO PREF (ID, NAME) VALUES (26,'京都府');
INSERT INTO PREF (ID, NAME) VALUES (27,'大阪府');
INSERT INTO PREF (ID, NAME) VALUES (28,'兵庫県');
INSERT INTO PREF (ID, NAME) VALUES (29,'奈良県');
INSERT INTO PREF (ID, NAME) VALUES (30,'和歌山県');
INSERT INTO PREF (ID, NAME) VALUES (31,'鳥取県');
INSERT INTO PREF (ID, NAME) VALUES (32,'島根県');
INSERT INTO PREF (ID, NAME) VALUES (33,'岡山県');
INSERT INTO PREF (ID, NAME) VALUES (34,'広島県');
INSERT INTO PREF (ID, NAME) VALUES (35,'山口県');
INSERT INTO PREF (ID, NAME) VALUES (36,'徳島県');
INSERT INTO PREF (ID, NAME) VALUES (37,'香川県');
INSERT INTO PREF (ID, NAME) VALUES (38,'愛媛県');
INSERT INTO PREF (ID, NAME) VALUES (39,'高知県');
INSERT INTO PREF (ID, NAME) VALUES (40,'福岡県');
INSERT INTO PREF (ID, NAME) VALUES (41,'佐賀県');
INSERT INTO PREF (ID, NAME) VALUES (42,'長崎県');
INSERT INTO PREF (ID, NAME) VALUES (43,'熊本県');
INSERT INTO PREF (ID, NAME) VALUES (44,'大分県');
INSERT INTO PREF (ID, NAME) VALUES (45,'宮崎県');
INSERT INTO PREF (ID, NAME) VALUES (46,'鹿児島県');
INSERT INTO PREF (ID, NAME) VALUES (47,'沖縄県');

